@startuml
[*] --> Boutique
Boutique : Le joueur accède à la boutique

Boutique --> ClickBuyButton : Le joueur fait un achat
ClickBuyButton --> Confirmation : Le joueur va voir si il peut acheter
Confirmation --> Reussite : Achat réussi
Confirmation --> Echec : Achat échoué (pas assez de pièces)
Reussite --> Boutique : Retour à la boutique
Echec --> Boutique : Retour à la boutique
Boutique --> RetourMenuPrincipal : Retour au menu principal
RetourMenuPrincipal --> [*] : Retour au menu principal
@enduml
