@startuml ObstacleState
[*] --> EnAttente
EnAttente : L'obstacle est prêt à apparaître

EnAttente --> Deplacement : L'obstacle est généré et commence à se déplacer
Deplacement --> HorsChamp : L'obstacle sort de son champ de définiton
HorsChamp --> Détruit : L'obstacle est détruit

state Deplacement {
    [*] --> EnMouvement
    EnMouvement : L'obstacle se déplace
}
@enduml
