@startuml PlayerState
[*] --> EnAttente
EnAttente : Le joueur est sur l'écran de démarrage ou de sélection

EnAttente --> EnJeu : Le joueur commence la partie
EnJeu --> Mort : Collision avec un obstacle mortel ou capturé par l'aigle
EnJeu --> Pause : Le joueur met le jeu en pause

Pause --> EnJeu : Le joueur reprend la partie
Mort --> [*] : Le jeu retourne à l'écran de fin de partie ou de démarrage

state EnJeu {
    [*] --> Deplacement : Le joueur se déplace
    Deplacement --> Collison : Le joueur entre en collision avec un obstacle
    Collison --> Mort : Collision mortelle
    Collison --> Deplacement : Collision non mortelle
}
@enduml
