@startuml
actor Player

(Player) -> (Open Shop) : Open the skin shop
(Open Shop) -> (Buy Skin): Click
(Player) -> (Buy Skin) : Buy a skin
(Buy Skin) -> (Check Skin) : Check if the player has enough coins
(Check Skin) -> (Unlock Skin) : Unlock the skin
(Check Skin) -> (Insufficient Coins) : Insufficient coins

@enduml
