@startuml
actor Player

Player -> (Start game) : Start the game
(Start game) -> (Select Difficulty) : on the pannel
Player -> (Select Difficulty) : Select the level of difficulty
(Select Difficulty) -> (System) : Send the selected difficulty
(System) -> (Apply Difficulty) : Apply the selected difficulty

@enduml
