@startuml
|Système|
start
:Générer les troncs et nénuphars;
:Définir la direction et la vitesse;

repeat
    :Déplacer les objets;
    :Vérifier les collisions;
repeat while (Jeu en cours?)
stop
@enduml
