@startuml
|Système|
start
:Début de la partie;
:Sélectionner aléatoirement un type de terrain;
:Placer les obstacles sur le terrain;

repeat
    :Générer une nouvelle ligne de terrain;
    :Placer les objets sur le terrain;
repeat while (Jeu en cours?)
stop
@enduml
