@startuml failAcivity
start
:Le joueur rencontre un obstacle mortel;
:Le chrono s'arrête;
:Les données sont enregistrées;
:Le panel de fin de partie s'affiche;
:Afficher le score final;
:Proposer de relancer ou de quitter;
stop
@enduml
