@startuml generationActivity
start
:Définir les points d'apparition des objets;
repeat
  :Attendre un intervalle de temps aléatoire;
  :Sélectionner un type d'objet à faire apparaître en fonction du terrain;
  :Instancier l'objet à la position d'apparition;
  :Définir la direction et la vitesse de l'objet;
  :Déplacer l'objet selon la logique de déplacement;
repeat while (La partie n'est pas terminée)
stop
@enduml
