@startuml menuByPauseActivity
start
:Lancer le jeu;
:Lancer une partie;
:Appuyer sur le boutton "Pause";
:Appuyer sur "Retourner au menu" dans le menu de pause;
:Confirmer l'action;
:Rechargement de la scène;
stop
@enduml
