@startuml
start
:Lancer le jeu;
:Aller dans le menu classement;
:Afficher le classement des joueurs;
:Sélectionner une difficulté;
:Affihcer le classement des joueurs pour cette difficulté;
:Afficher les scores correspondants;
stop
@enduml
