@startuml eagleUC
|Système|
start
:Vérifier l'inactivité ou le recul du joueur;
if (Inactivité ou recul de 3 cases) then (oui)
    :Apparition de l'aigle;
    :S'emparer du joueur;
    :Terminer la partie;
else (non)
    stop
endif
stop
@enduml
