@startuml terrainGeneratorUC
|Système|
start
:Début de la partie;

repeat
    :Sélectionner aléatoirement un type de terrain du theme;
    :Determiner combien de terrain seront générés;
    :Générer la(les) nouvelle(s) ligne(s) de terrain;
    :Placer les obstacles sur le(s) terrain(s);
    if (Joueur a avancé?) then (oui)
        :Supprimer la première ligne générée de la scène;
    endif
repeat while (Jeu en cours?)
stop
@enduml
