@startuml classDiagram
class Player extends MLAgent.Agent{
    -name: string
    -skin: SkinData
    -score: int
    -position: Vector3
    -isAI: bool
    +Move(direction: int): void
    +CollectCoin(): void
    +Destroy(): void
    +SetAI(isAI: bool): void
    +SetPlayerName(): void
    +GetPlayerPosition(): void
}

class SkinData{
    -Model: GameObject 
    -theme: string 
    -unlocked: bool 
    -sprite: Sprite 
    -selected: bool 
}

class Terrain {
    -type: string
    -obstacles: List<Obstacle>
    -possibleTerrains: List<GameObject>
    -probabilityOfSpawning: float
    -maxInSuccessive: int
    +Generate(): void
}

class Obstacle {
    -position: Vector3
    +Instantiate(): void
    +Destroy(): void
}

class MovingObject extends Obstacle{
    -speed: float
    -direction: int
    -type: GameObject
    -isLog: bool
    +Move(): void
    +SetSpeed(): void
    +SetDirection(): void
}

class Vehicle extends MovingObject {
    +KillPlayer(): void
}

enum VehicleType extends Vehicle {
    FastCar
    BigCar
    MidCar
    LittleCar
    Truck
    Train
}

class Logs extends MovingObject {
    -loglenght: float
    +AttachPlayer(): void
}

class StationaryObject extends Obstacle {
    +Activate(): void
}

class Coin {
    -value: int
    -position: Vector3
    +Collect(): void
}

class Game {
    -player: Player
    -terrain: Terrain
    -theme : Theme
    -coins: List<Coin>
    -difficulty
    +Start(): void
    +Pause(): void
    +End(): void
    +SetDifficulty(): void
}

Player "1" -- "0..*" Coin
Player "0..1" -- "1" SkinData
Terrain "1" -- "0..*" Obstacle
Game "1" -- "1" Player
Game "1" -- "0..*" Terrain
Terrain "1" -- "0..*" Coin
@enduml
